/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-28 04:39:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myBoard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1679893946172L));
    _jspx_dependants.put("jar:file:/C:/workspace/villageHall/VillageHall/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>마을회관</title>\r\n");
      out.write("\r\n");
      out.write("    <link\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\"\r\n");
      out.write("    />\r\n");
      out.write("    \r\n");
      out.write("    <link rel=\"stylesheet\"\r\n");
      out.write("    href= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/my-page-myBoard.css\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- fontawesome -->\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://kit.fontawesome.com/2f1bf0eac7.js\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>   \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("        <!-- header include -->\r\n");
      out.write("  \r\n");
      out.write("        <!-- 내부 접근 절대 경로 -->\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("        <!-- 바디 부분 시작 -->\r\n");
      out.write("        <section class=\"body\">\r\n");
      out.write("          \r\n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/leftBody.jsp", out, false);
      out.write(" \r\n");
      out.write("  \r\n");
      out.write("          <!-- 메인 콘텐츠------------------------- -->\r\n");
      out.write("          <section class=\"right-body\">\r\n");
      out.write("          내글목록 게시판 확인 \r\n");
      out.write("            <h2>마이페이지</h2>\r\n");
      out.write("          <hr />\r\n");
      out.write("          <!-- 탭 메뉴 -->\r\n");
      out.write("          <div class=\"tab\">\r\n");
      out.write("            <button class=\"tablinks active\" data-tab=\"myContent\">내 글</button>\r\n");
      out.write("            <button class=\"tablinks\" data-tab=\"myComment\">내 댓글</button>\r\n");
      out.write("            <button class=\"tablinks\" data-tab=\"myLike\">내 좋아요</button>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myContent\" class=\"tabcontent\">\r\n");
      out.write("              <h3>내 글 목록</h3>\r\n");
      out.write("              <table class=\"contentTable\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th>글번호</th>\r\n");
      out.write("                    <th>제목</th>\r\n");
      out.write("                    <th>작성일</th>\r\n");
      out.write("                    <th>조회</th>\r\n");
      out.write("                    <th>좋아요</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody id=\"content\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("\r\n");
      out.write("<!-- 페이징용 tfoot -->\r\n");
      out.write("                <tfoot>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td colspan=\"5\">\r\n");
      out.write("                      <div id=\"pagination\"></div>\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tfoot>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myComment\" class=\"tabcontent\">\r\n");
      out.write("              <h3>내 댓글</h3>\r\n");
      out.write("              <table class=\"commentTable\">\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <span>반갑습니다</span><br />\r\n");
      out.write("                        <span>2023.09.08</span><br />\r\n");
      out.write("                        <span>오늘 가입했습니다~</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <hr />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <span>좋은정보 감사합니다</span><br />\r\n");
      out.write("                        <span>2022.09.08</span><br />\r\n");
      out.write("                        <span>강남역에 새로운 라멘집 오픈했어요!</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <hr />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <span>아 우산 챙겨야겠네요 ㅠ</span><br />\r\n");
      out.write("                        <span>2021.07.08</span><br />\r\n");
      out.write("                        <span>오늘 하루종일 폭우래요 우산챙기세요</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <hr />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">\r\n");
      out.write("                        <span>감사합니다 ~~</span><br />\r\n");
      out.write("                        <span>2021.02.08</span><br />\r\n");
      out.write("                        <span>무료나눔합니다(역삼역 근처에서!)</span>\r\n");
      out.write("                      </a>\r\n");
      out.write("                      <hr />\r\n");
      out.write("                    </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myLike\" class=\"tabcontent\">\r\n");
      out.write("              <h3>내 좋아요</h3>\r\n");
      out.write("              <table class=\"likeTable\">\r\n");
      out.write("                <thead>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <th>글번호</th>\r\n");
      out.write("                    <th>제목</th>\r\n");
      out.write("                    <th>작성일</th>\r\n");
      out.write("                    <th>작성자</th>\r\n");
      out.write("                    <th>조회</th>\r\n");
      out.write("                    <th>좋아요</th>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("\r\n");
      out.write("                <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>1231</td>\r\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\r\n");
      out.write("                    <td>2023.03.04</td>\r\n");
      out.write("                    <td>역삼불주먹</td>\r\n");
      out.write("                    <td>1181</td>\r\n");
      out.write("                    <td>18</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>993</td>\r\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\r\n");
      out.write("                    <td>2023.02.08</td>\r\n");
      out.write("                    <td>고양이만세</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>19</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>951</td>\r\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\r\n");
      out.write("                    <td>2023.01.14</td>\r\n");
      out.write("                    <td>민수짱123</td>\r\n");
      out.write("                    <td>141</td>\r\n");
      out.write("                    <td>58</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>831</td>\r\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\r\n");
      out.write("                    <td>2023.01.01</td>\r\n");
      out.write("                    <td>개발하조만세</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>777</td>\r\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\r\n");
      out.write("                    <td>2022.11.12</td>\r\n");
      out.write("                    <td>아이디도일이다</td>\r\n");
      out.write("                    <td>181</td>\r\n");
      out.write("                    <td>98</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>556</td>\r\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\r\n");
      out.write("                    <td>2022.08.24</td>\r\n");
      out.write("                    <td>가나다라마바</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>512</td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>2022.06.03</td>\r\n");
      out.write("                    <td>티없이맑은눈</td>\r\n");
      out.write("                    <td>121</td>\r\n");
      out.write("                    <td>12</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>323</td>\r\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\r\n");
      out.write("                    <td>2022.05.14</td>\r\n");
      out.write("                    <td>캣캣캣캣</td>\r\n");
      out.write("                    <td>11</td>\r\n");
      out.write("                    <td>1</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td>123</td>\r\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\r\n");
      out.write("                    <td>2022.03.04</td>\r\n");
      out.write("                    <td>작성자만세</td>\r\n");
      out.write("                    <td>111</td>\r\n");
      out.write("                    <td>8</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </tbody>\r\n");
      out.write("              </table>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </section>\r\n");
      out.write("          <!-- 메인 콘텐츠 종료-------------------------------------- -->\r\n");
      out.write("        </section>\r\n");
      out.write("      </main>\r\n");
      out.write("  \r\n");
      out.write("      <!-- footer include -->\r\n");
      out.write("      <!-- 내부 접근 절대 경로 -->\r\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("  \r\n");
      out.write("      <!-- jQuery 라이브러리 추가 -->\r\n");
      out.write("      <script\r\n");
      out.write("        src=\"https://code.jquery.com/jquery-3.6.0.js\"\r\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\r\n");
      out.write("        crossorigin=\"anonymous\"\r\n");
      out.write("      ></script>\r\n");
      out.write("  \r\n");
      out.write("      <!-- main.js 연결 -->\r\n");
      out.write("      <!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script> -->\r\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/my-page-myBoard.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
