/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-29 05:47:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mypage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myLike_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680059251000L));
    _jspx_dependants.put("jar:file:/C:/workspace/villageHall/VillageHall/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>마을회관</title>\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("    rel=\"stylesheet\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\"\n");
      out.write("    />\n");
      out.write("    \n");
      out.write("    <link rel=\"stylesheet\"\n");
      out.write("    href= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/myPage-myBoard.css\" />\n");
      out.write("\n");
      out.write("    <!-- fontawesome -->\n");
      out.write("    <script\n");
      out.write("      src=\"https://kit.fontawesome.com/2f1bf0eac7.js\"\n");
      out.write("      crossorigin=\"anonymous\"\n");
      out.write("    ></script>   \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <main>\n");
      out.write("        <!-- header include -->\n");
      out.write("  \n");
      out.write("        <!-- 내부 접근 절대 경로 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("        <!-- 바디 부분 시작 -->\n");
      out.write("        <section class=\"body\">\n");
      out.write("          \n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/leftBody.jsp", out, false);
      out.write(" \n");
      out.write("  \n");
      out.write("          <!-- 메인 콘텐츠------------------------- -->\n");
      out.write("          <section class=\"right-body\">\n");
      out.write("          \n");
      out.write("            <h2>마이페이지</h2>\n");
      out.write("          <hr>\n");
      out.write("          <!-- 탭 메뉴 -->\n");
      out.write("          <div class=\"tab\">\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/myBoard\"> 내 글</a>\n");
      out.write("          	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/myComment\"> 내 댓글</a>\n");
      out.write("          	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mypage/myLike\"> 내 좋아요</a>\n");
      out.write("\n");
      out.write("            <div class=\"tabContent\">\n");
      out.write("              <h3>내 좋아요</h3>\n");
      out.write("              <table class=\"likeTable\">\n");
      out.write("                <thead>\n");
      out.write("                  <tr>\n");
      out.write("                    <th>글번호</th>\n");
      out.write("                    <th>제목</th>\n");
      out.write("                    <th>작성일</th>\n");
      out.write("                    <th>작성자</th>\n");
      out.write("                    <th>조회</th>\n");
      out.write("                    <th>좋아요</th>\n");
      out.write("                  </tr>\n");
      out.write("                </thead>\n");
      out.write("\n");
      out.write("                <tbody>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>1231</td>\n");
      out.write("                    <td><a href=\"#\">여기는 데이터불러오는 걸로 수정필요</a></td>\n");
      out.write("                    <td>2023.03.04</td>\n");
      out.write("                    <td>역삼불주먹</td>\n");
      out.write("                    <td>1181</td>\n");
      out.write("                    <td>18</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>993</td>\n");
      out.write("                    <td><a href=\"#\">테스트2</a></td>\n");
      out.write("                    <td>2023.02.08</td>\n");
      out.write("                    <td>고양이만세</td>\n");
      out.write("                    <td>111</td>\n");
      out.write("                    <td>19</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>951</td>\n");
      out.write("                    <td><a href=\"#\">가나다라마바사</a></td>\n");
      out.write("                    <td>2023.01.14</td>\n");
      out.write("                    <td>민수짱123</td>\n");
      out.write("                    <td>141</td>\n");
      out.write("                    <td>58</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>831</td>\n");
      out.write("                    <td><a href=\"#\">새해복 많이받으세요</a></td>\n");
      out.write("                    <td>2023.01.01</td>\n");
      out.write("                    <td>개발하조만세</td>\n");
      out.write("                    <td>11</td>\n");
      out.write("                    <td>11</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>777</td>\n");
      out.write("                    <td><a href=\"#\">맛집추천좀해주세요</a></td>\n");
      out.write("                    <td>2022.11.12</td>\n");
      out.write("                    <td>아이디도일이다</td>\n");
      out.write("                    <td>181</td>\n");
      out.write("                    <td>98</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>556</td>\n");
      out.write("                    <td><a href=\"#\">할말이없다</a></td>\n");
      out.write("                    <td>2022.08.24</td>\n");
      out.write("                    <td>가나다라마바</td>\n");
      out.write("                    <td>111</td>\n");
      out.write("                    <td>8</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>512</td>\n");
      out.write("                    <td>\n");
      out.write("                      <a href=\"#\">2호선 시위때문에 다들 일찍 출발하세요</a>\n");
      out.write("                    </td>\n");
      out.write("                    <td>2022.06.03</td>\n");
      out.write("                    <td>티없이맑은눈</td>\n");
      out.write("                    <td>121</td>\n");
      out.write("                    <td>12</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>323</td>\n");
      out.write("                    <td><a href=\"#\">역삼역 맛집 정보</a></td>\n");
      out.write("                    <td>2022.05.14</td>\n");
      out.write("                    <td>캣캣캣캣</td>\n");
      out.write("                    <td>11</td>\n");
      out.write("                    <td>1</td>\n");
      out.write("                  </tr>\n");
      out.write("                  <tr>\n");
      out.write("                    <td>123</td>\n");
      out.write("                    <td><a href=\"#\">가입했습니다 ^^</a></td>\n");
      out.write("                    <td>2022.03.04</td>\n");
      out.write("                    <td>작성자만세</td>\n");
      out.write("                    <td>111</td>\n");
      out.write("                    <td>8</td>\n");
      out.write("                  </tr>\n");
      out.write("                </tbody>\n");
      out.write("              </table>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          </section>\n");
      out.write("          <!-- 메인 콘텐츠 종료-------------------------------------- -->\n");
      out.write("        </section>\n");
      out.write("      </main>\n");
      out.write("  \n");
      out.write("      <!-- footer include -->\n");
      out.write("      <!-- 내부 접근 절대 경로 -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("      <!-- jQuery 라이브러리 추가 -->\n");
      out.write("      <script\n");
      out.write("        src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("        crossorigin=\"anonymous\"\n");
      out.write("      ></script>\n");
      out.write("  \n");
      out.write("      <!-- main.js 연결 -->\n");
      out.write("      <!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script> -->\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/myPage-myBoard.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
