/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-30 09:43:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680143416627L));
    _jspx_dependants.put("jar:file:/Users/sujinchoi/workspace/villageHall/VillageHall/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("    <title>마을회관</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/login-page.css\" />\n");
      out.write("\n");
      out.write("    <!-- fontawesome -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/2f1bf0eac7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <main>\n");
      out.write("      <!-- header include -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("      <!-- 바디 부분 시작 -->\n");
      out.write("      <section class=\"body\">\n");
      out.write("        <!-- 메인 콘텐츠 -->\n");
      out.write("        <section class=\"right-body\">\n");
      out.write("          <!--콘텐츠 작성 영역-->\n");
      out.write("          <section class=\"content\">\n");
      out.write("            <h1 class=\"sign-in-text\">로그인</h1>\n");
      out.write("          </section>\n");
      out.write("\n");
      out.write("          <section class=\"content-2\">\n");
      out.write("            <!--로그인시 필요한 정보 기입 영역-->\n");
      out.write("            <form action=\"#\" name=\"sign-in-form\">\n");
      out.write("              <fieldset id=\"sign-in-area\">\n");
      out.write("                <section class=\"sign-in-1\">\n");
      out.write("                  <!--아이디-->\n");
      out.write("                  <fieldset id=\"id-area\">\n");
      out.write("                    <i class=\"fa-regular fa-user\"></i>\n");
      out.write("                    <input\n");
      out.write("                      type=\"text\"\n");
      out.write("                      name=\"inputId\"\n");
      out.write("                      class=\"input-text\"\n");
      out.write("                    /><br />\n");
      out.write("                  </fieldset>\n");
      out.write("                  <br />\n");
      out.write("\n");
      out.write("                  <!--비밀번호-->\n");
      out.write("                  <fieldset id=\"pw-area\">\n");
      out.write("                    <i class=\"fa-solid fa-lock\"></i>\n");
      out.write("                    <input\n");
      out.write("                      type=\"password\"\n");
      out.write("                      name=\"inputPw\"\n");
      out.write("                      class=\"input-text\"\n");
      out.write("                    /><br /><br />\n");
      out.write("                  </fieldset>\n");
      out.write("                  <br />\n");
      out.write("\n");
      out.write("                  <!-- 로그인 버튼-->\n");
      out.write("                  <article class=\"signInBtn-article\">\n");
      out.write("                    <button class=\"signInBtn\">로그인</button>\n");
      out.write("                  </article>\n");
      out.write("                </section>\n");
      out.write("              </fieldset>\n");
      out.write("\n");
      out.write("              <!--비밀번호 찾기/ 아이디 찾기/ 회원가입 -->\n");
      out.write("              <br />\n");
      out.write("              <article class=\"id-pw-found\">\n");
      out.write("                <a href=\"../html/pw-find-page.html\" class=\"found\"\n");
      out.write("                  >비밀번호찾기</a\n");
      out.write("                >\n");
      out.write("                <a href=\"sign-up-page.html\" class=\"found\">회원가입</a>\n");
      out.write("              </article>\n");
      out.write("\n");
      out.write("              <!--카카오로 로그인-->\n");
      out.write("\n");
      out.write("              <article class=\"sign-in-article-1\">\n");
      out.write("                <a href=\"javascript:void(0)\" onclick=\"kakaoLogin();\">\n");
      out.write("                  <img src=\"/src/kakao_login_medium_wide.png\" />\n");
      out.write("                </a>\n");
      out.write("              </article>\n");
      out.write("            </form>\n");
      out.write("          </section>\n");
      out.write("        </section>\n");
      out.write("      </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!-- footer include -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- jQuery 라이브러리 추가 -->\n");
      out.write("    <script\n");
      out.write("      src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("      integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("      crossorigin=\"anonymous\"\n");
      out.write("    ></script>\n");
      out.write("\n");
      out.write("    <!-- main.js 연결 -->\n");
      out.write("    <!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script> -->\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
