/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-30 09:43:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FAQ_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680143416627L));
    _jspx_dependants.put("jar:file:/Users/sujinchoi/workspace/villageHall/VillageHall/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>마을회관</title>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/FAQ-page.css\"/>\n");
      out.write("\n");
      out.write("    <!-- fontawesome -->\n");
      out.write("    <script src=\"https://kit.fontawesome.com/2f1bf0eac7.js\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <main>\n");
      out.write("        <!-- header include -->\n");
      out.write("  \n");
      out.write("        <!-- 내부 접근 절대 경로 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("        <!-- 바디 부분 시작 -->\n");
      out.write("        <section class=\"body\">\n");
      out.write("          \n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/leftBody.jsp", out, false);
      out.write(" \n");
      out.write("  \n");
      out.write("          <!-- 메인 콘텐츠 -->\n");
      out.write("         <section class=\"right-body\">\n");
      out.write("           \n");
      out.write("          <!--FAQ 질문 검색 부분-->\n");
      out.write("          <article class=\"FAQ-search\">\n");
      out.write("            <!--FAQ 질문 검색창-->\n");
      out.write("            <form action=\"#\" name=\"FAQ-search-form\">\n");
      out.write("              <h3 class=\"FAQ-text\">FAQ 자주 묻는 질문</h3>\n");
      out.write("\n");
      out.write("              <fieldset class=\"FAQ-search-fieldset\">\n");
      out.write("                <input\n");
      out.write("                  type=\"search\"\n");
      out.write("                  id=\"query\"\n");
      out.write("                  name=\"query\"\n");
      out.write("                  autocomplete=\"off\"\n");
      out.write("                  placeholder=\"무엇이 궁금하실까요?\"\n");
      out.write("                />\n");
      out.write("\n");
      out.write("                <!--FAQ 질문 검색버튼-->\n");
      out.write("                <button\n");
      out.write("                  id=\"FAQ-search-btn\"\n");
      out.write("                  class=\"fa-solid fa-magnifying-glass\"\n");
      out.write("                ></button>\n");
      out.write("              </fieldset>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("            <!--FAQ 카테고리-->\n");
      out.write("          </article>\n");
      out.write("\n");
      out.write("          <article class=\"category-article\">\n");
      out.write("            <a href=\"#\" class=\"category\" data-tab=\"signUp\"> 회원가입 </a>\n");
      out.write("            <a href=\"#\" class=\"category\" data-tab=\"logIn\"> 로그인 </a>\n");
      out.write("            <a href=\"#\" class=\"category\" data-tab=\"content\"> 게시글 </a>\n");
      out.write("            <a href=\"#\" class=\"category\" data-tab=\"etc\"> 기타 </a>\n");
      out.write("          </article>\n");
      out.write("\n");
      out.write("          <article class=\"FAQ-board-article\">\n");
      out.write("\n");
      out.write("            <div class=\"FAQ-board\" id=\"signUp\">\n");
      out.write("                  <ul class=\"FAQ-Ul\">\n");
      out.write("\n");
      out.write("                    <li> 구분</li>\n");
      out.write("                    <li> 제목</li>\n");
      out.write("                    <li> 작성일</li>\n");
      out.write("                    <li> 조회</li>\n");
      out.write("                    <li> 좋아요</li>\n");
      out.write("    \n");
      out.write("                  </ul>\n");
      out.write("                  <hr>\n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li> 회원 탈퇴를 취소하고 싶습니다.</li>\n");
      out.write("                    <li>2020.01.23</li>\n");
      out.write("                    <li>3578</li>\n");
      out.write("                    <li>77</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>       \n");
      out.write("                </div>\n");
      out.write("  \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li> 회원 탈퇴는 어떻게 하나요?</li>\n");
      out.write("                    <li>2020.01.23</li>\n");
      out.write("                    <li>3239</li>\n");
      out.write("                    <li>89</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li> 메인 로그인이 안됩니다.</li>\n");
      out.write("                    <li>2021.10.21</li>\n");
      out.write("                    <li>2280</li>\n");
      out.write("                    <li>56</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>소셜 로그인(카카오) 연동을 해제하고 싶어요</li>\n");
      out.write("                    <li>2021.11.23</li>\n");
      out.write("                    <li>1120</li>\n");
      out.write("                    <li>80</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("  \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>아이디와 비밀번호가 기억나지 않아요</li>\n");
      out.write("                    <li>2021.11.30</li>\n");
      out.write("                    <li>1002</li>\n");
      out.write("                    <li>78</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>회원정보 수정은 어디서 하나요?</li>\n");
      out.write("                    <li>2021.09.11</li>\n");
      out.write("                    <li>998</li>\n");
      out.write("                    <li>76</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>비밀번호 변경은 어디서 하나요?</li>\n");
      out.write("                    <li>2022.02.22</li>\n");
      out.write("                    <li>865</li>\n");
      out.write("                    <li>43</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>이메일 인증 시 이미 존재해나는 이메일이라고 <br>\n");
      out.write("                      뜰 때는 어떻게 해야하나요?</li>\n");
      out.write("                    <li>2022.06.23</li>\n");
      out.write("                    <li>724</li>\n");
      out.write("                    <li>27</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>본인 인증이 안되는 경우에는 어떻게 해야하나요?</li>\n");
      out.write("                    <li>2022.06.23</li>\n");
      out.write("                    <li>665</li>\n");
      out.write("                    <li>21</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("    \n");
      out.write("                  <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                    <li><strong>가입/인증</strong></li>\n");
      out.write("                    <li>본인 인증을 잘못했는데 초기화 가능한가요?</li>\n");
      out.write("                    <li>2022.11.23</li>\n");
      out.write("                    <li>332</li>\n");
      out.write("                    <li>64</li>\n");
      out.write("                  </ul>\n");
      out.write("                  <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("      \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"FAQ-board\" id=\"logIn\">\n");
      out.write("              <ul class=\"FAQ-Ul\">\n");
      out.write("\n");
      out.write("                <li> 구분</li>\n");
      out.write("                <li> 제목</li>\n");
      out.write("                <li> 작성일</li>\n");
      out.write("                <li> 조회</li>\n");
      out.write("                <li> 좋아요</li>\n");
      out.write("\n");
      out.write("              </ul>\n");
      out.write("              <hr>\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li> 회원 탈퇴를 취소하고 싶습니다.</li>\n");
      out.write("                <li>2020.01.23</li>\n");
      out.write("                <li>3578</li>\n");
      out.write("                <li>77</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>    \n");
      out.write("                </div>          \n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li> 회원 탈퇴는 어떻게 하나요?</li>\n");
      out.write("                <li>2020.01.23</li>\n");
      out.write("                <li>3239</li>\n");
      out.write("                <li>89</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li> 메인 로그인이 안됩니다.</li>\n");
      out.write("                <li>2021.10.21</li>\n");
      out.write("                <li>2280</li>\n");
      out.write("                <li>56</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>소셜 로그인(카카오) 연동을 해제하고 싶어요</li>\n");
      out.write("                <li>2021.11.23</li>\n");
      out.write("                <li>1120</li>\n");
      out.write("                <li>80</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>아이디와 비밀번호가 기억나지 않아요</li>\n");
      out.write("                <li>2021.11.30</li>\n");
      out.write("                <li>1002</li>\n");
      out.write("                <li>78</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>회원정보 수정은 어디서 하나요?</li>\n");
      out.write("                <li>2021.09.11</li>\n");
      out.write("                <li>998</li>\n");
      out.write("                <li>76</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>비밀번호 변경은 어디서 하나요?</li>\n");
      out.write("                <li>2022.02.22</li>\n");
      out.write("                <li>865</li>\n");
      out.write("                <li>43</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>이메일 인증 시 이미 존재해나는 이메일이라고 <br>\n");
      out.write("                  뜰 때는 어떻게 해야하나요?</li>\n");
      out.write("                <li>2022.06.23</li>\n");
      out.write("                <li>724</li>\n");
      out.write("                <li>27</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>본인 인증이 안되는 경우에는 어떻게 해야하나요?</li>\n");
      out.write("                <li>2022.06.23</li>\n");
      out.write("                <li>665</li>\n");
      out.write("                <li>21</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>본인 인증을 잘못했는데 초기화 가능한가요?</li>\n");
      out.write("                <li>2022.11.23</li>\n");
      out.write("                <li>332</li>\n");
      out.write("                <li>64</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("            </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("              <div class=\"FAQ-board\" id=\"content\">\n");
      out.write("                <ul class=\"FAQ-Ul\">\n");
      out.write("\n");
      out.write("                  <li> 구분</li>\n");
      out.write("                  <li> 제목</li>\n");
      out.write("                  <li> 작성일</li>\n");
      out.write("                  <li> 조회</li>\n");
      out.write("                  <li> 좋아요</li>\n");
      out.write("\n");
      out.write("                </ul>\n");
      out.write("                <hr>\n");
      out.write("                <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                  <li><strong>탈퇴/기타</strong></li>\n");
      out.write("                  <li> 회원 탈퇴를 취소하고 싶습니다.</li>\n");
      out.write("                  <li>2020.01.23</li>\n");
      out.write("                  <li>3578</li>\n");
      out.write("                  <li>77</li>\n");
      out.write("                  </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>탈퇴/기타</strong></li>\n");
      out.write("                <li> 회원 탈퇴는 어떻게 하나요?</li>\n");
      out.write("                <li>2020.01.23</li>\n");
      out.write("                <li>3239</li>\n");
      out.write("                <li>89</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li> 메인 로그인이 안됩니다.</li>\n");
      out.write("                <li>2021.10.21</li>\n");
      out.write("                <li>2280</li>\n");
      out.write("                <li>56</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>소셜 로그인(카카오) 연동을 해제하고 싶어요</li>\n");
      out.write("                <li>2021.11.23</li>\n");
      out.write("                <li>1120</li>\n");
      out.write("                <li>80</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>아이디와 비밀번호가 기억나지 않아요</li>\n");
      out.write("                <li>2021.11.30</li>\n");
      out.write("                <li>1002</li>\n");
      out.write("                <li>78</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>회원정보 수정은 어디서 하나요?</li>\n");
      out.write("                <li>2021.09.11</li>\n");
      out.write("                <li>998</li>\n");
      out.write("                <li>76</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>로그인/정보</strong></li>\n");
      out.write("                <li>비밀번호 변경은 어디서 하나요?</li>\n");
      out.write("                <li>2022.02.22</li>\n");
      out.write("                <li>865</li>\n");
      out.write("                <li>43</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>가입/인증</strong></li>\n");
      out.write("                <li>이메일 인증 시 이미 존재해나는 이메일이라고 <br>\n");
      out.write("                  뜰 때는 어떻게 해야하나요?</li>\n");
      out.write("                <li>2022.06.23</li>\n");
      out.write("                <li>724</li>\n");
      out.write("                <li>27</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>가입/인증</strong></li>\n");
      out.write("                <li>본인 인증이 안되는 경우에는 어떻게 해야하나요?</li>\n");
      out.write("                <li>2022.06.23</li>\n");
      out.write("                <li>665</li>\n");
      out.write("                <li>21</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("              <ul class=\"FAQ-Ul FAQ-Ul1\">\n");
      out.write("                <li><strong>가입/인증</strong></li>\n");
      out.write("                <li>본인 인증을 잘못했는데 초기화 가능한가요?</li>\n");
      out.write("                <li>2022.11.23</li>\n");
      out.write("                <li>332</li>\n");
      out.write("                <li>64</li>\n");
      out.write("              </ul>\n");
      out.write("              <div class=\"p\">\n");
      out.write("                <p>\n");
      out.write("                  <hr>\n");
      out.write("                  개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                  관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                  이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                  기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                  다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                  <hr>\n");
      out.write("                </p>              \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("            </div>\n");
      out.write("            </article>\n");
      out.write("          </article>\n");
      out.write("          </section>\n");
      out.write("        </section>\n");
      out.write("      </main>\n");
      out.write("  \n");
      out.write("      <!-- footer include -->\n");
      out.write("      <!-- 내부 접근 절대 경로 -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("      <!-- jQuery 라이브러리 추가 -->\n");
      out.write("      <script\n");
      out.write("        src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("        crossorigin=\"anonymous\"\n");
      out.write("      ></script>\n");
      out.write("  \n");
      out.write("      <!-- FAQ-page.js 연결 -->\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/FAQ.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
