/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-29 05:47:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class notice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1680059251000L));
    _jspx_dependants.put("jar:file:/C:/workspace/villageHall/VillageHall/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>마을회관</title>\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("    rel=\"stylesheet\"\n");
      out.write("    href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/Notice-page.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <!-- fontawesome -->\n");
      out.write("    <script\n");
      out.write("      src=\"https://kit.fontawesome.com/2f1bf0eac7.js\"\n");
      out.write("      crossorigin=\"anonymous\"\n");
      out.write("    ></script>   \n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <main>\n");
      out.write("        <!-- header include -->\n");
      out.write("  \n");
      out.write("        <!-- 내부 접근 절대 경로 -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("        <!-- 바디 부분 시작 -->\n");
      out.write("        <section class=\"body\">\n");
      out.write("          \n");
      out.write("          ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/leftBody.jsp", out, false);
      out.write(" \n");
      out.write("  \n");
      out.write("          <!-- 메인 콘텐츠 -->\n");
      out.write("          <section class=\"right-body\">\n");
      out.write("          \n");
      out.write("            <h3 id=\"Notice-name\">공지사항</h3>\n");
      out.write("            <hr>\n");
      out.write("              <div id=\"myContent\" class=\"tabcontent\">\n");
      out.write("  \n");
      out.write("                <ul class=\"Notice-Ul\">\n");
      out.write("                  <li>글번호</li>\n");
      out.write("                  <li class=\"cell\">제목</li>\n");
      out.write("                  <li class=\"cell\">작성일</li>\n");
      out.write("                  <li class=\"cell\">조회</li>\n");
      out.write("                  <li class=\"cell\">좋아요</li>\n");
      out.write("                </ul>\n");
      out.write("                \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>1231</li>\n");
      out.write("                  <li>개인정보처리방침 개정 내용 사전안내</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                      <hr>\n");
      out.write("                      개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                      관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                      이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                      기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                      다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>              \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>993</li>\n");
      out.write("                  <li>위치기반 서비스 개정 내용 사전안내</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                    <p>\n");
      out.write("                      <strong>마을회관 <이용약관의 효력 및 변경> 위치기반서비스</strong>\n");
      out.write("                      <hr>\n");
      out.write("                      본 약관은 회원(마을회관 위치기반서비스 약관에 동의한 자를 말합니다)<br>\n");
      out.write("                      이 본 홈페이지 마을회관이 제공하는 위치기반서비스(이하 \"서비스\"라고 합니다) 를<br>\n");
      out.write("                      이용함에 있어 운영자와 회원의 권리·의무 및 책임사항을 규정함을 목적으로 합니다.\n");
      out.write("                      <hr>\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>951</li>\n");
      out.write("                  <li>서비스 점검 시간 사전 안내</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                  \n");
      out.write("                  <p>\n");
      out.write("                    <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                    <hr>\n");
      out.write("                    개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                    관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                    이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                    기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                    다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                    <hr>\n");
      out.write("                  </p>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>831</li>\n");
      out.write("                  <li>인터넷 익스플로러(IE) 지원 종료 안내</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                  \n");
      out.write("                  <p>\n");
      out.write("                    <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                    <hr>\n");
      out.write("                    개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                    관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                    이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                    기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                    다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                    <hr>\n");
      out.write("                  </p>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>556</li>\n");
      out.write("                  <li>저작권 도용 관련 게시글 안내 공지</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                  \n");
      out.write("                  <p>\n");
      out.write("                    <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                    <hr>\n");
      out.write("                    개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                    관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                    이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                    기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                    다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                    <hr>\n");
      out.write("                  </p>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\">\n");
      out.write("                  <li>512</li>\n");
      out.write("                  <li>5년 이상 미사용 계정 휴면처리 안내 공지</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                  \n");
      out.write("                  <p>\n");
      out.write("                    <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                    <hr>\n");
      out.write("                    개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                    관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                    이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                    기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                    다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                    <hr>\n");
      out.write("                  </p>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("                <ul class=\"Notice-Ul Notice-Ul1\" >\n");
      out.write("                  <li>323</li>\n");
      out.write("                  <li>서비스 점검 시간 사전 안내(~12/20)</li>\n");
      out.write("                  <li>2020.12.02</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                  <li>19</li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"p\">\n");
      out.write("                  \n");
      out.write("                  <p>\n");
      out.write("                    <strong>개인정보보호위원회 <개인정보보호 포털> 개인정보 처리방침</strong>\n");
      out.write("                    <hr>\n");
      out.write("                    개인정보보호위원회는 정보주체의 자유와 권리 보호를 위해 ｢개인정보 보호법｣ 및 <br>\n");
      out.write("                    관계 법령이 정한 바를 준수하여, 적법하게 개인정보를 처리하고 안전하게 관리하고 있습니다.\n");
      out.write("                    이에 ｢개인정보 보호법｣ 제30조에 따라 정보주체에게 개인정보 처리에 관한 절차 및 <br>\n");
      out.write("                    기준을 안내하고, 이와 관련한 고충을 신속하고 원활하게 처리할 수 있도록 하기 위하여 <br>\n");
      out.write("                    다음과 같이 개인정보 처리방침을 수립·공개합니다.\n");
      out.write("                    <hr>\n");
      out.write("                  </p>\n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("                \n");
      out.write("              </div>\n");
      out.write("  \n");
      out.write("            </div>  \n");
      out.write("            \n");
      out.write("          </section>\n");
      out.write("        </section>\n");
      out.write("      </main>\n");
      out.write("  \n");
      out.write("      <!-- footer include -->\n");
      out.write("      <!-- 내부 접근 절대 경로 -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("      <!-- jQuery 라이브러리 추가 -->\n");
      out.write("      <script\n");
      out.write("        src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("        integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("        crossorigin=\"anonymous\"\n");
      out.write("      ></script>\n");
      out.write("  \n");
      out.write("      <!-- Notice-page.js 연결 -->\n");
      out.write("      <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/Notice-page.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
