/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
<<<<<<< HEAD:VillageHall/src/main/webapp/WEB-INF/jspwork/org/apache/jsp/WEB_002dINF/views/common/header_jsp.java
<<<<<<< HEAD
 * Generated at: 2023-03-26 08:02:09 UTC
=======
 * Generated at: 2023-03-26 13:08:06 UTC
>>>>>>> 84a02c348ed7b0f07fba665755d68cba424971b6
=======
 * Generated at: 2023-03-27 09:14:39 UTC
>>>>>>> b80a14a6afbf92887548ede5b7b1ce6247a849ec:VillageHall/src/main/webapp/WEB-INF/org/apache/jsp/WEB_002dINF/views/common/header_jsp.java
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<header>\n");
      out.write("  <!-- 클릭시 메인으로 이동하는 로고 -->\n");
      out.write("  <section>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/logo.png\" id=\"home-logo\" />\n");
      out.write("\n");
      out.write("    </a>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <section>\n");
      out.write("    <article class=\"search-area\">\n");
      out.write("      <!-- form 내부 input 태그 값을 서버 또는 페이지로 전달 -->\n");
      out.write("      <form action=\"#\" name=\"search-form\">\n");
      out.write("        <fieldset>\n");
      out.write("          <input\n");
      out.write("            type=\"search\"\n");
      out.write("            id=\"query\"\n");
      out.write("            name=\"query\"\n");
      out.write("            autocomplete=\"off\"\n");
      out.write("            placeholder=\"검색어를 입력해주세요\"\n");
      out.write("          />\n");
      out.write("\n");
      out.write("          <!-- 검색버튼 -->\n");
      out.write("          <button id=\"search-btn\" class=\"fa-solid fa-magnifying-glass\"></button>\n");
      out.write("        </fieldset>\n");
      out.write("      </form>\n");
      out.write("    </article>\n");
      out.write("  </section>\n");
      out.write("\n");
      out.write("  <!-- 로그인 / 회원가입 -->\n");
      out.write("  <section class=\"login-signup-area\">\n");
      out.write("    <div>\n");
      out.write("      <!-- 자물쇠 아이콘 -->\n");
      out.write("      <a href=\"/html/sign-in-page.html\" id=\"login\" class=\"fa-solid fa-lock\"\n");
      out.write("        >&nbsp;로그인</a\n");
      out.write("      >\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <a href=\"/html/sign-up-page.html\" id=\"signup\">회원가입</a>\n");
      out.write("  </section>\n");
      out.write("</header>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
