/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-26 03:56:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"UTF-8\" />\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.7.min.js\"></script>\n");
      out.write("\n");
      out.write("    <link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      href=\"resources/css/main.css\"\n");
      out.write("    />\n");
      out.write("    <link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      href=\"resources/css/main-page.css\"\n");
      out.write("    />\n");
      out.write("    <link\n");
      out.write("      rel=\"stylesheet\"\n");
      out.write("      href=\"resources/css/weather.css\"\n");
      out.write("    />\n");
      out.write("\n");
      out.write("    <!-- ì íì¨êº¼ ì§ë api key -->\n");
      out.write("    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=196b8c346b121bd08b2a475bfa001dd0\"\n");
      out.write("    ></script>\n");
      out.write("    <script\n");
      out.write("      type=\"text/javascript\"\n");
      out.write("      src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=196b8c346b121bd08b2a475bfa001dd0&libraries=LIBRARY\"\n");
      out.write("    ></script>\n");
      out.write("\n");
      out.write("    <!-- fontawesome -->\n");
      out.write("    <script\n");
      out.write("      src=\"https://kit.fontawesome.com/2f1bf0eac7.js\"\n");
      out.write("      crossorigin=\"anonymous\"\n");
      out.write("    ></script>\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <main>\n");
      out.write("      <!-- header include -->\n");
      out.write("\n");
      out.write("      <!-- ë´ë¶ ì ê·¼ ì ë ê²½ë¡ -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("      <!-- ë°ë ë¶ë¶ ìì -->\n");
      out.write("      <section class=\"body\">\n");
      out.write("        <section class=\"left-body\">\n");
      out.write("          <article>\n");
      out.write("            <!-- ì´ë¯¸ì§ + ë¡ê·¸ì¸ -->\n");
      out.write("\n");
      out.write("            <img src=\"../src/profile.png\" /><br />\n");
      out.write("            <a href=\"/html/sign-in-page.html\" id=\"body-login\"> ë¡ê·¸ì¸</a>\n");
      out.write("          </article>\n");
      out.write("          <!-- ë¤ë¹ (ë©ë´ë°)-->\n");
      out.write("          <nav>\n");
      out.write("            <ul>\n");
      out.write("              <li>\n");
      out.write("                <i class=\"fa-solid fa-house\" id=\"nav-home\"></i>\n");
      out.write("                <a href=\"/html/main-page.html\">í</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <i class=\"fa-regular fa-bell\" id=\"nav-notice\"></i>\n");
      out.write("                <a href=\"#\"> ê³µì§ì¬í­</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <i class=\"fa-solid fa-globe\" id=\"nav-all\"></i>\n");
      out.write("                <a href=\"/html/All-board.html\">ì ì²´ê¸</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <i class=\"fa-solid fa-bookmark\" id=\"nav-popular\"></i>\n");
      out.write("                <a href=\"#\">ì¸ê¸°ê¸</a>\n");
      out.write("              </li>\n");
      out.write("              <li>\n");
      out.write("                <i class=\"fa-regular fa-circle-question\" id=\"nav-faq\"></i>\n");
      out.write("                <a href=\"/html/FAQ-page.html\">FAQ</a>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </nav>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <!-- ë©ì¸ ì½íì¸  -->\n");
      out.write("        <section class=\"right-body\">\n");
      out.write("          <!-- ì§ë ë¶ë¶ -->\n");
      out.write("          <section>\n");
      out.write("            <div>\n");
      out.write("              <label for=\"category\" class=\"category\">ì¹´íê³ ë¦¬:</label>\n");
      out.write("              <select onchange=\"showMarkersByCategory(this.value)\">\n");
      out.write("                <option value=\"ì ì²´\">ì ì²´ê¸</option>\n");
      out.write("                <option value=\"ì´ì\">ì´ì</option>\n");
      out.write("                <option value=\"ë§ì§\">ë§ì§</option>\n");
      out.write("                <option value=\"ì·¨ë¯¸\">ì·¨ë¯¸</option>\n");
      out.write("                <option value=\"ì¹ëª©\">ì¹ëª©</option>\n");
      out.write("                <option value=\"ì¶ì²\">ì¶ì²</option>\n");
      out.write("                <option value=\"ê¸°í\">ê¸°í</option>\n");
      out.write("              </select>\n");
      out.write("            </div>\n");
      out.write("            <div\n");
      out.write("              id=\"map\"\n");
      out.write("              style=\"width: auto; height: 500px; margin-left: 15px\"\n");
      out.write("            ></div>\n");
      out.write("          </section>\n");
      out.write("\n");
      out.write("          <!-- ê³µì§+ì¸ê¸°ê¸ -->\n");
      out.write("          <section class=\"notice-fave\">\n");
      out.write("            <!-- ê³µì§ì¬í­ -->\n");
      out.write("            <div class=\"notice-box\">\n");
      out.write("              <div><p>ê³µì§ì¬í­</p></div>\n");
      out.write("              <div>\n");
      out.write("                <table class=\"notice-content\">\n");
      out.write("                  <thead>\n");
      out.write("                    <tr>\n");
      out.write("                      <th>ì ëª©</th>\n");
      out.write("                      <th>ì¡°íì</th>\n");
      out.write("                    </tr>\n");
      out.write("                  </thead>\n");
      out.write("                  <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìì¹ê¸°ë°ìë¹ì¤ë°©ì¹¨ ê°ì  ë´ì© ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 53 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìë¹ì¤ ì ê² ìê° ì¬ì  ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 39 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ì¸í°ë· ìµì¤íë¡ë¬(IE) ì§ì ì¢ë£ ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 27 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          5ë ì´ì ë¯¸ì¬ì© ê³ì  í´ë©´ì²ë¦¬ ìë´ ê³µì§\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 11 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìì¹ê¸°ë°ìë¹ì¤ë°©ì¹¨ ê°ì  ë´ì© ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 53 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìë¹ì¤ ì ê² ìê° ì¬ì  ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 39 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ì¸í°ë· ìµì¤íë¡ë¬(IE) ì§ì ì¢ë£ ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 27 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </tbody>\n");
      out.write("                </table>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- ì¸ê¸°ê¸ -->\n");
      out.write("            <div class=\"fave-box\">\n");
      out.write("              <div><p>ì¸ê¸°ê¸</p></div>\n");
      out.write("              <div>\n");
      out.write("                <table class=\"fave-content\">\n");
      out.write("                  <thead>\n");
      out.write("                    <tr>\n");
      out.write("                      <th>ì ëª©</th>\n");
      out.write("                      <th>ì¡°íì</th>\n");
      out.write("                    </tr>\n");
      out.write("                  </thead>\n");
      out.write("                  <tbody>\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìì¹ê¸°ë°ìë¹ì¤ë°©ì¹¨ ê°ì  ë´ì© ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 53 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìë¹ì¤ ì ê² ìê° ì¬ì  ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 39 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ì¸í°ë· ìµì¤íë¡ë¬(IE) ì§ì ì¢ë£ ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 27 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          5ë ì´ì ë¯¸ì¬ì© ê³ì  í´ë©´ì²ë¦¬ ìë´ ê³µì§\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 11 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ê°ì¸ì ë³´ì²ë¦¬ë°©ì¹¨ ê°ì  ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 66 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìì¹ê¸°ë°ìë¹ì¤ë°©ì¹¨ ê°ì  ë´ì© ì¬ì ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 53 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ìë¹ì¤ ì ê² ìê° ì¬ì  ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 39 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                      <td>\n");
      out.write("                        <a href=\"#\" title=\"ì¬ì©ê¿í\">\n");
      out.write("                          ì¸í°ë· ìµì¤íë¡ë¬(IE) ì§ì ì¢ë£ ìë´\n");
      out.write("                        </a>\n");
      out.write("                      </td>\n");
      out.write("                      <td><a href=\"#\" title=\"ì¬ì©ê¿í\"> 27 </a></td>\n");
      out.write("                    </tr>\n");
      out.write("                  </tbody>\n");
      out.write("                </table>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </section>\n");
      out.write("\n");
      out.write("          <!-- ë ì¨ -->\n");
      out.write("          <section class=\"weather\">\n");
      out.write("            <div class=\"box\">\n");
      out.write("              <!-- ë ì§ -->\n");
      out.write("              <div class=\"FirstBox\">\n");
      out.write("                <h1 class=\"date\">ì¤ëìë ì¨</h1>\n");
      out.write("              </div>\n");
      out.write("              <!-- ë ì¨ ìë ¥ -->\n");
      out.write("              <div class=\"SecondBox\">\n");
      out.write("                <div class=\"Sbox1\">\n");
      out.write("                  <div class=\"cicon\"></div>\n");
      out.write("                  <div class=\"main\"></div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"ctemp\"><h4>íì¬ì¨ë</h4></div>\n");
      out.write("                <div class=\"clowtemp\"><h4>ìµì ì¨ë</h4></div>\n");
      out.write("                <div class=\"humidity\"><h4>ìµë</h4></div>\n");
      out.write("                <div class=\"mi\">\n");
      out.write("                  <h4>ë¯¸ì¸ë¨¼ì§</h4>\n");
      out.write("                  <div class=\"aqi\"></div>\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </section>\n");
      out.write("        </section>\n");
      out.write("      </section>\n");
      out.write("    </main>\n");
      out.write("\n");
      out.write("    <!-- footer include -->\n");
      out.write("    <!-- ë´ë¶ ì ê·¼ ì ë ê²½ë¡ -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- jQuery ë¼ì´ë¸ë¬ë¦¬ ì¶ê° -->\n");
      out.write("    <script\n");
      out.write("      src=\"https://code.jquery.com/jquery-3.6.0.js\"\n");
      out.write("      integrity=\"sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=\"\n");
      out.write("      crossorigin=\"anonymous\"\n");
      out.write("    ></script>\n");
      out.write("\n");
      out.write("    <!-- main.js ì°ê²° -->\n");
      out.write("    <!-- <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script> -->\n");
      out.write("\n");
      out.write("    <script src=\"/js/main-page.js\"></script>\n");
      out.write("    <script src=\"/js/weather.js\"></script>\n");
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main-page-Map-API.js\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
